mytool/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.HomeView.as_view(), name="home"),
    path("users/", include("search_users.urls")),
]

search_users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", views.UserTV.as_view(), name="index"),
    path("ids/<str:pk>/", views.UseridFV.as_view(), name="list"),
    path("ids/ban/<str:pk>/", views.UserbanDelV.as_view(), name="ban"),
]

search_users/models.py
from django.db import models
from django_mysql.models import ListCharField

# Create your models here.
class User(models.Model):
    user_id = models.CharField("USERID", max_length=10, primary_key=True)
    name = models.CharField("NAME", max_length=10)
    created_at = models.DateField(auto_now_add=True)
    gold = models.IntegerField("GOLD")
    level = models.IntegerField("LEVEL")
    inventory = ListCharField(
        base_field=models.CharField(max_length=10), size=10, max_length=(10 * 11)
    )

    def __str__(self):
        return self.user_id

mytool/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home.html"

search_users/views.py
import json

from django.http import JsonResponse

# Create your views here.
from django.views.generic import TemplateView
from django.views.generic.edit import BaseFormView, BaseDeleteView

from search_users.models import User


class UserTV(TemplateView):
    template_name = "search_users/user_index.html"


class UseridFV(BaseFormView):
    def get_object(self, queryset=None):
        if self.kwargs["pk"] != "":
            return User.objects.filter(user_id=self.kwargs["pk"]).values()
        else:
            return User.objects.none()

    def get(self, request, *args, **kwargs):
        user_info = self.get_object()
        if not user_info:
            return JsonResponse(data={})
        return JsonResponse(data=user_info[0])

    def post(self, request, *args, **kwargs):
        user_info = self.get_object()[0]
        if not user_info:
            return JsonResponse(data={})
        new_item = json.loads(self.request.body)
        ((new_key, new_value),) = new_item.items()
        if new_key != "inventory":
            new_item = {new_key: int(new_value)}
        User.objects.filter(pk=user_info["user_id"]).update(**new_item)
        return JsonResponse(data=user_info)


class UserbanDelV(BaseDeleteView):
    def delete(self, request, *args, **kwargs):
        user_id = self.kwargs["pk"]
        if user_id != "":
            user = User.objects.get(user_id=user_id)
            user.delete()
        return JsonResponse(data={})

search_users/templates/search_users/user_index.html
{% extends 'base.html' %}
{% block title %}Django - Vue - MySQL{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .user_row:hover{
            background-color:#fefefe;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
        .removeBtn:hover{
            color: red;
        }

        i:hover{
            cursor: pointer;
        }
    </style>
{% endblock %}

{% block content %}
<div id='app'>

    <br>
    <h1>게임 유저 검색</h1>
    <br>

    <div class="input-group mb-3">
      <input type="text" class="form-control" placeholder="ID" v-model.trim="user_id"
          v-on:keyup.enter="search_user(user_id)">
      <button class="btn btn-outline-secondary" v-on:click="search_user(user_id)">search</button>
    </div>

    <br>
    <h3>
        검색 결과
        <span v-on:click="search_user(user_id)">
            <i class="fas fa-redo"></i>
        </span>
    </h3>
    <br>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Created at</th>
          <th scope="col">Gold</th>
          <th scope="col">Level</th>
          <th scope="col">Inventory</th>
        </tr>
      </thead>
      <tbody>
        <tr class="user_row" v-on:click="detail_user(user_id)">
          <th scope="row">[[ user_info.user_id ]]</th>
          <td>[[ user_info.name ]]</td>
          <td>[[ user_info.created_at ]]</td>
          <td>[[ user_info.gold ]]</td>
          <td>[[ user_info.level ]]</td>
          <td>[[ user_info.inventory ]]</td>
          <td></td>
        </tr>
      </tbody>
    </table>

    <table class="table table-dark" v-show="detail_show">
      <thead class="thead-dark">
        <tr>
          <th scope="col">이름</th>
          <th scope="col">값</th>
          <th scope="col">액션</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row"> gold </th>
          <td><input type="text" class="form-control" v-model.trim="gold"></td>
          <td><button class="btn btn-info btn-sm" v-on:click="update_data('gold', gold)">수정</button></td>
        </tr>
        <tr>
          <th scope="row"> level </th>
          <td><input type="text" class="form-control" v-model.trim="level"></td>
          <td><button class="btn btn-info btn-sm" v-on:click="update_data('level', level)">수정</button></td>
        </tr>
        <tr>
          <th scope="row"> inventory </th>
          <td><input type="text" class="form-control" v-model.trim="inventory"></td>
          <td><button class="btn btn-info btn-sm" v-on:click="update_data('inventory', inventory)">수정</button></td>
        </tr>
      </tbody>
    </table>
    <button type="button" class="btn btn-danger" v-show="detail_show" v-on:click="delete_data(user_id)">제재</button>
</div>
{% endblock %}

{% block extra-script %}
<script src="https://unpkg.com/vue/dist/vue.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>

    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = 'X-CSRFToken';

    var vm = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            user_id: '',
            user_info: {},
            detail_show: false,
            gold: '',
            level: '',
            inventory: [],
        },
        methods: {
            search_user: function(user_id){
              console.log("search_user()...");
              if (user_id == '') return;

              var vm = this;
              axios.get('/users/ids/'+ user_id + '/')
                  .then(function(res){
                    console.log("SEARCH GET RES", res);
                    vm.user_info = res.data;
                  })
                  .catch(function(err){
                    console.log("SEARCH ERR", err);
                  })
            },
            detail_user:function(user_id){

              if (this.user_info["user_id"] == undefined) return;

              if (this.detail_show == false){
                this.detail_show = true;
              }
              else{
                this.detail_show = false;
              }
            },

            update_data:function(k, v){
              console.log("UPDATE ", k, v);
              if (confirm("수정하시겠습니까?") == false) return;

              var vm = this;
              var postData = {[k] : v};
              console.log(postData);
              axios.post('/users/ids/' + this.user_info['user_id'] + '/', postData)
                  .then(function(res){
                    console.log("UPDATE POST RES", res);
                    vm.search_user(vm.user_info["user_id"]);
                  })
                  .catch(function(err){
                    console.log("UPDATE POST ERR", err);
                  })
              this.v = '';
              this.gold = '';
              this.level = '';
              this.inventory = '';

            },

            delete_data:function(user_id){
              console.log("delete_data()...");
              if (confirm("삭제하시겠습니까?") == false) return;

              var vm = this;
              axios.delete('/users/ids/ban/' + this.user_info['user_id'] + '/')
                  .then(function(res){
                    console.log("DELETE RES", res);
                    vm.search_user(vm.user_info["user_id"]);
                    vm.detail_show = false;
                  })
                  .catch(function(err){
                    console.log("DELETE ERR", err);
                  })

            },
        },

    })
</script>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}home.html{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/2fd93f26de.js" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    {% block extra-style %}{% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">운영툴</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:index' %}">유저관리</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">로그(tobe)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">푸쉬 알람(tobe)</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Util</a>
            <ul class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}